-- NUBulldogsExchange: Product size variants migration
-- Run in Supabase SQL Editor. Non-destructive (IF NOT EXISTS / ADD COLUMN IF NOT EXISTS).
-- Uses bigint to match existing products.id (integer), NOT uuid.

-- 1) Size variants
CREATE TABLE IF NOT EXISTS public.product_variants (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    product_id bigint NOT NULL
        REFERENCES public.products(id)
        ON DELETE CASCADE,
    size text NOT NULL,
    sku text UNIQUE,
    stock_quantity integer NOT NULL DEFAULT 0
        CHECK (stock_quantity >= 0),
    price_adjustment numeric(10,2) NOT NULL DEFAULT 0,
    status text NOT NULL DEFAULT 'Active'
        CHECK (status IN ('Active', 'Inactive')),
    created_at timestamptz NOT NULL DEFAULT now(),
    updated_at timestamptz NOT NULL DEFAULT now(),
    UNIQUE (product_id, size)
);

CREATE INDEX IF NOT EXISTS idx_product_variants_product_id
    ON public.product_variants (product_id);

CREATE INDEX IF NOT EXISTS idx_product_variants_active
    ON public.product_variants (product_id)
    WHERE status = 'Active';

-- 2) Cart: ensure variant_id exists (app already uses it)
DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM information_schema.columns
        WHERE table_schema = 'public'
          AND table_name = 'cart_items'
          AND column_name = 'variant_id'
    ) THEN
        ALTER TABLE public.cart_items
            ADD COLUMN variant_id bigint NULL
                REFERENCES public.product_variants(id)
                ON DELETE SET NULL;
    END IF;
END $$;

-- 3) Order items: size snapshot for history
ALTER TABLE public.order_items
    ADD COLUMN IF NOT EXISTS variant_id bigint NULL
        REFERENCES public.product_variants(id)
        ON DELETE SET NULL;

ALTER TABLE public.order_items
    ADD COLUMN IF NOT EXISTS size text NULL;

ALTER TABLE public.order_items
    ADD COLUMN IF NOT EXISTS variant_sku text NULL;

-- 4) Privileges (required — RLS alone is not enough; without GRANT you get
--    "permission denied for table product_variants")
GRANT SELECT, INSERT, UPDATE, DELETE ON TABLE public.product_variants
    TO anon, authenticated;
GRANT ALL ON TABLE public.product_variants TO service_role;
GRANT USAGE, SELECT ON SEQUENCE public.product_variants_id_seq
    TO anon, authenticated, service_role;

-- 5) RLS (align with products — adjust role checks to match your project)
ALTER TABLE public.product_variants ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS product_variants_select_active ON public.product_variants;
CREATE POLICY product_variants_select_active
    ON public.product_variants
    FOR SELECT
    TO authenticated, anon
    USING (status = 'Active');

DROP POLICY IF EXISTS product_variants_admin_all ON public.product_variants;
CREATE POLICY product_variants_admin_all
    ON public.product_variants
    FOR ALL
    TO authenticated
    USING (
        EXISTS (
            SELECT 1
            FROM public.users_with_roles u
            WHERE u.id = auth.uid()
              AND lower(u.role) IN ('admin', 'staff')
        )
    )
    WITH CHECK (
        EXISTS (
            SELECT 1
            FROM public.users_with_roles u
            WHERE u.id = auth.uid()
              AND lower(u.role) IN ('admin', 'staff')
        )
    );

-- 6) Checkout RPC note:
-- Update place_checkout_order to:
--   - accept p_items[].variant_id and p_items[].selected_size
--   - when variant_id is set: deduct product_variants.stock_quantity,
--     then set products.stock = SUM(active variant stocks)
--   - when variant_id is null: keep existing product-level stock deduction
--   - insert order_items.variant_id, size, variant_sku snapshot
-- See docs/sql/place_checkout_order_variants_patch.sql for a reference patch.
